name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ] # development, release, production v8

jobs:
  build_ci: 
    uses: crisarbebvc/lab_devops_templates/.github/workflows/CD-deployment_build-java.yml@main
    secrets: inherit